
draw_dust = false;
// Setting image angle
//if its generated by the random generator dont use the original tree angle
if(!global.generatingEnvironment){
	image_angle = global.birch_tree_angle;
} else {
	//randomize rotation
	image_angle = irandom(360);
}


// Scale
scale = .6;

z = 0;
health_ = 2;
event_inherited();

// Spawning
bounce = true;
spawnCount = 0;

canHit = true;

isKey = false;