draw_dust = false;
isFungi = false;

//if its generated by the random generator dont use the original tree angle
if(!global.generatingEnvironment){
	image_angle = global.spruce_tree_angle;
} else {
	//randomize rotation
	image_angle = irandom(360);
	
	if(irandom_range(0, 3) == 0)
		isFungi = true;
}

if(isFungi)
	sprite_index = s_spruce_stump_fungi;

z = 0;
health_ = 2;
event_inherited();

// Spawning
bounce = true;
spawnCount = 0;
stackCount = 0;

canHit = true;

isKey = false;